(* Generated by transpile_ocaml.py from _artifacts/kernel_cost_model.json. *)
(* The planner calls predict_latency with explicit, unboxed float arguments. *)

let tree_0 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  0.23500132600000001

let tree_1 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  0.215417892

let tree_2 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  0.19746640300000001

let tree_3 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  0.18101087199999999

let tree_4 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  0.16592662

let tree_5 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  0.152099401

let tree_6 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  0.13942444300000001

let tree_7 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  0.12780574

let predict_latency f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  0.0 +. 1.0 *. (tree_0 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_1 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_2 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_3 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_4 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_5 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_6 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_7 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9)
