(* Generated by transpile_ocaml.py from _artifacts/cost-model-repair-2026-08-26/model-relative-delta-16x3.json. *)
(* The planner calls predict_latency with explicit, unboxed float arguments. *)

let tree_0 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  if Float.is_nan f5 then
    if Float.is_nan f0 then
      if Float.is_nan f6 then
        0.013339392800000001
      else if f6 < 16.0 then
        0.0086854649700000008
      else
        0.013339392800000001
    else if f0 < 32.0 then
      if Float.is_nan f2 then
        0.041327837899999997
      else if f2 < 2048.0 then
        0.013245823800000001
      else
        0.041327837899999997
    else
      if Float.is_nan f6 then
        0.013339392800000001
      else if f6 < 16.0 then
        0.0086854649700000008
      else
        0.013339392800000001
  else if f5 < 32.0 then
    if Float.is_nan f0 then
      if Float.is_nan f5 then
        0.00057796057099999997
      else if f5 < 16.0 then
        0.0039729196600000001
      else
        0.00057796057099999997
    else if f0 < 13.0 then
      if Float.is_nan f5 then
        0.000208874728
      else if f5 < 16.0 then
        -0.0057679535800000004
      else
        0.000208874728
    else
      if Float.is_nan f5 then
        0.00057796057099999997
      else if f5 < 16.0 then
        0.0039729196600000001
      else
        0.00057796057099999997
  else
    if Float.is_nan f0 then
      if Float.is_nan f6 then
        0.013339392800000001
      else if f6 < 16.0 then
        0.0086854649700000008
      else
        0.013339392800000001
    else if f0 < 32.0 then
      if Float.is_nan f2 then
        0.041327837899999997
      else if f2 < 2048.0 then
        0.013245823800000001
      else
        0.041327837899999997
    else
      if Float.is_nan f6 then
        0.013339392800000001
      else if f6 < 16.0 then
        0.0086854649700000008
      else
        0.013339392800000001

let tree_1 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  if Float.is_nan f5 then
    if Float.is_nan f0 then
      if Float.is_nan f6 then
        0.012675018999999999
      else if f6 < 16.0 then
        0.0082528814700000008
      else
        0.012675018999999999
    else if f0 < 32.0 then
      if Float.is_nan f1 then
        0.050107341299999997
      else if f1 < 4096.0 then
        0.0178145226
      else
        0.050107341299999997
    else
      if Float.is_nan f6 then
        0.012675018999999999
      else if f6 < 16.0 then
        0.0082528814700000008
      else
        0.012675018999999999
  else if f5 < 32.0 then
    if Float.is_nan f0 then
      if Float.is_nan f5 then
        0.00054915260999999996
      else if f5 < 16.0 then
        0.0037748930000000001
      else
        0.00054915260999999996
    else if f0 < 13.0 then
      if Float.is_nan f5 then
        0.000198511945
      else if f5 < 16.0 then
        -0.0054817916799999996
      else
        0.000198511945
    else
      if Float.is_nan f5 then
        0.00054915260999999996
      else if f5 < 16.0 then
        0.0037748930000000001
      else
        0.00054915260999999996
  else
    if Float.is_nan f0 then
      if Float.is_nan f6 then
        0.012675018999999999
      else if f6 < 16.0 then
        0.0082528814700000008
      else
        0.012675018999999999
    else if f0 < 32.0 then
      if Float.is_nan f1 then
        0.050107341299999997
      else if f1 < 4096.0 then
        0.0178145226
      else
        0.050107341299999997
    else
      if Float.is_nan f6 then
        0.012675018999999999
      else if f6 < 16.0 then
        0.0082528814700000008
      else
        0.012675018999999999

let tree_2 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  if Float.is_nan f5 then
    if Float.is_nan f0 then
      if Float.is_nan f0 then
        0.0111796567
      else if f0 < 128.0 then
        0.0062513598199999999
      else
        0.0111796567
    else if f0 < 32.0 then
      if Float.is_nan f2 then
        0.037984471800000003
      else if f2 < 2048.0 then
        0.011299284200000001
      else
        0.037984471800000003
    else
      if Float.is_nan f0 then
        0.0111796567
      else if f0 < 128.0 then
        0.0062513598199999999
      else
        0.0111796567
  else if f5 < 32.0 then
    if Float.is_nan f0 then
      if Float.is_nan f5 then
        0.00052178051600000001
      else if f5 < 16.0 then
        0.0035867360399999999
      else
        0.00052178051600000001
    else if f0 < 13.0 then
      if Float.is_nan f5 then
        0.00018866326700000001
      else if f5 < 16.0 then
        -0.0052098268599999999
      else
        0.00018866326700000001
    else
      if Float.is_nan f5 then
        0.00052178051600000001
      else if f5 < 16.0 then
        0.0035867360399999999
      else
        0.00052178051600000001
  else
    if Float.is_nan f0 then
      if Float.is_nan f0 then
        0.0111796567
      else if f0 < 128.0 then
        0.0062513598199999999
      else
        0.0111796567
    else if f0 < 32.0 then
      if Float.is_nan f2 then
        0.037984471800000003
      else if f2 < 2048.0 then
        0.011299284200000001
      else
        0.037984471800000003
    else
      if Float.is_nan f0 then
        0.0111796567
      else if f0 < 128.0 then
        0.0062513598199999999
      else
        0.0111796567

let tree_3 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  if Float.is_nan f5 then
    if Float.is_nan f0 then
      if Float.is_nan f6 then
        0.011548289999999999
      else if f6 < 16.0 then
        0.0073463991300000003
      else
        0.011548289999999999
    else if f0 < 32.0 then
      if Float.is_nan f1 then
        0.046408414799999999
      else if f1 < 4096.0 then
        0.015699049499999999
      else
        0.046408414799999999
    else
      if Float.is_nan f6 then
        0.011548289999999999
      else if f6 < 16.0 then
        0.0073463991300000003
      else
        0.011548289999999999
  else if f5 < 32.0 then
    if Float.is_nan f0 then
      if Float.is_nan f5 then
        0.00049577275100000004
      else if f5 < 16.0 then
        0.0034079577300000002
      else
        0.00049577275100000004
    else if f0 < 13.0 then
      if Float.is_nan f5 then
        0.00017930328600000001
      else if f5 < 16.0 then
        -0.0049513545800000001
      else
        0.00017930328600000001
    else
      if Float.is_nan f5 then
        0.00049577275100000004
      else if f5 < 16.0 then
        0.0034079577300000002
      else
        0.00049577275100000004
  else
    if Float.is_nan f0 then
      if Float.is_nan f6 then
        0.011548289999999999
      else if f6 < 16.0 then
        0.0073463991300000003
      else
        0.011548289999999999
    else if f0 < 32.0 then
      if Float.is_nan f1 then
        0.046408414799999999
      else if f1 < 4096.0 then
        0.015699049499999999
      else
        0.046408414799999999
    else
      if Float.is_nan f6 then
        0.011548289999999999
      else if f6 < 16.0 then
        0.0073463991300000003
      else
        0.011548289999999999

let tree_4 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  if Float.is_nan f5 then
    if Float.is_nan f0 then
      if Float.is_nan f0 then
        0.0105503844
      else if f0 < 256.0 then
        0.0063596353899999999
      else
        0.0105503844
    else if f0 < 32.0 then
      if Float.is_nan f2 then
        0.034932326499999999
      else if f2 < 2048.0 then
        0.0095744840800000008
      else
        0.034932326499999999
    else
      if Float.is_nan f0 then
        0.0105503844
      else if f0 < 256.0 then
        0.0063596353899999999
      else
        0.0105503844
  else if f5 < 32.0 then
    if Float.is_nan f0 then
      if Float.is_nan f5 then
        0.00047106132799999999
      else if f5 < 16.0 then
        0.0032380910100000002
      else
        0.00047106132799999999
    else if f0 < 13.0 then
      if Float.is_nan f5 then
        0.000170407569
      else if f5 < 16.0 then
        -0.0047057061499999999
      else
        0.000170407569
    else
      if Float.is_nan f5 then
        0.00047106132799999999
      else if f5 < 16.0 then
        0.0032380910100000002
      else
        0.00047106132799999999
  else
    if Float.is_nan f0 then
      if Float.is_nan f0 then
        0.0105503844
      else if f0 < 256.0 then
        0.0063596353899999999
      else
        0.0105503844
    else if f0 < 32.0 then
      if Float.is_nan f2 then
        0.034932326499999999
      else if f2 < 2048.0 then
        0.0095744840800000008
      else
        0.034932326499999999
    else
      if Float.is_nan f0 then
        0.0105503844
      else if f0 < 256.0 then
        0.0063596353899999999
      else
        0.0105503844

let tree_5 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  if Float.is_nan f5 then
    if Float.is_nan f0 then
      if Float.is_nan f6 then
        0.010525926
      else if f6 < 16.0 then
        0.0065333130800000003
      else
        0.010525926
    else if f0 < 32.0 then
      if Float.is_nan f1 then
        0.043010719099999997
      else if f1 < 4096.0 then
        0.0138079925
      else
        0.043010719099999997
    else
      if Float.is_nan f6 then
        0.010525926
      else if f6 < 16.0 then
        0.0065333130800000003
      else
        0.010525926
  else if f5 < 32.0 then
    if Float.is_nan f0 then
      if Float.is_nan f5 then
        0.00044758160900000002
      else if f5 < 16.0 then
        0.0030766907100000002
      else
        0.00044758160900000002
    else if f0 < 13.0 then
      if Float.is_nan f5 then
        0.00016195327
      else if f5 < 16.0 then
        -0.0044722445299999998
      else
        0.00016195327
    else
      if Float.is_nan f5 then
        0.00044758160900000002
      else if f5 < 16.0 then
        0.0030766907100000002
      else
        0.00044758160900000002
  else
    if Float.is_nan f0 then
      if Float.is_nan f6 then
        0.010525926
      else if f6 < 16.0 then
        0.0065333130800000003
      else
        0.010525926
    else if f0 < 32.0 then
      if Float.is_nan f1 then
        0.043010719099999997
      else if f1 < 4096.0 then
        0.0138079925
      else
        0.043010719099999997
    else
      if Float.is_nan f6 then
        0.010525926
      else if f6 < 16.0 then
        0.0065333130800000003
      else
        0.010525926

let tree_6 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  if Float.is_nan f5 then
    if Float.is_nan f0 then
      if Float.is_nan f0 then
        0.00923429523
      else if f0 < 128.0 then
        0.0047338176500000004
      else
        0.00923429523
    else if f0 < 32.0 then
      if Float.is_nan f2 then
        0.032144796099999998
      else if f2 < 2048.0 then
        0.0080482754899999995
      else
        0.032144796099999998
    else
      if Float.is_nan f0 then
        0.00923429523
      else if f0 < 128.0 then
        0.0047338176500000004
      else
        0.00923429523
  else if f5 < 32.0 then
    if Float.is_nan f0 then
      if Float.is_nan f5 then
        0.00042527230100000002
      else if f5 < 16.0 then
        0.0029233354100000001
      else
        0.00042527230100000002
    else if f0 < 13.0 then
      if Float.is_nan f5 then
        0.00015391835799999999
      else if f5 < 16.0 then
        -0.0042503657800000002
      else
        0.00015391835799999999
    else
      if Float.is_nan f5 then
        0.00042527230100000002
      else if f5 < 16.0 then
        0.0029233354100000001
      else
        0.00042527230100000002
  else
    if Float.is_nan f0 then
      if Float.is_nan f0 then
        0.00923429523
      else if f0 < 128.0 then
        0.0047338176500000004
      else
        0.00923429523
    else if f0 < 32.0 then
      if Float.is_nan f2 then
        0.032144796099999998
      else if f2 < 2048.0 then
        0.0080482754899999995
      else
        0.032144796099999998
    else
      if Float.is_nan f0 then
        0.00923429523
      else if f0 < 128.0 then
        0.0047338176500000004
      else
        0.00923429523

let tree_7 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  if Float.is_nan f5 then
    if Float.is_nan f1 then
      if Float.is_nan f0 then
        0.0087199434600000007
      else if f0 < 32.0 then
        0.0309802983
      else
        0.0087199434600000007
    else if f1 < 2048.0 then
      if Float.is_nan f2 then
        0.0087422272200000008
      else if f2 < 1024.0 then
        0.0014453701399999999
      else
        0.0087422272200000008
    else
      if Float.is_nan f0 then
        0.0087199434600000007
      else if f0 < 32.0 then
        0.0309802983
      else
        0.0087199434600000007
  else if f5 < 32.0 then
    if Float.is_nan f0 then
      if Float.is_nan f5 then
        0.00040407487500000001
      else if f5 < 16.0 then
        0.00277762394
      else
        0.00040407487500000001
    else if f0 < 13.0 then
      if Float.is_nan f5 then
        0.00014628212400000001
      else if f5 < 16.0 then
        -0.0040394952499999996
      else
        0.00014628212400000001
    else
      if Float.is_nan f5 then
        0.00040407487500000001
      else if f5 < 16.0 then
        0.00277762394
      else
        0.00040407487500000001
  else
    if Float.is_nan f1 then
      if Float.is_nan f0 then
        0.0087199434600000007
      else if f0 < 32.0 then
        0.0309802983
      else
        0.0087199434600000007
    else if f1 < 2048.0 then
      if Float.is_nan f2 then
        0.0087422272200000008
      else if f2 < 1024.0 then
        0.0014453701399999999
      else
        0.0087422272200000008
    else
      if Float.is_nan f0 then
        0.0087199434600000007
      else if f0 < 32.0 then
        0.0309802983
      else
        0.0087199434600000007

let tree_8 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  if Float.is_nan f5 then
    if Float.is_nan f1 then
      if Float.is_nan f0 then
        0.0087474724300000001
      else if f0 < 32.0 then
        0.038354840100000002
      else
        0.0087474724300000001
    else if f1 < 4096.0 then
      if Float.is_nan f2 then
        0.0108950427
      else if f2 < 1024.0 then
        0.00245473837
      else
        0.0108950427
    else
      if Float.is_nan f0 then
        0.0087474724300000001
      else if f0 < 32.0 then
        0.038354840100000002
      else
        0.0087474724300000001
  else if f5 < 32.0 then
    if Float.is_nan f0 then
      if Float.is_nan f5 then
        0.00038393409300000001
      else if f5 < 16.0 then
        0.0026391751599999999
      else
        0.00038393409300000001
    else if f0 < 13.0 then
      if Float.is_nan f1 then
        -0.0039000422700000001
      else if f1 < 2048.0 then
        0.000199981179
      else
        -0.0039000422700000001
    else
      if Float.is_nan f5 then
        0.00038393409300000001
      else if f5 < 16.0 then
        0.0026391751599999999
      else
        0.00038393409300000001
  else
    if Float.is_nan f1 then
      if Float.is_nan f0 then
        0.0087474724300000001
      else if f0 < 32.0 then
        0.038354840100000002
      else
        0.0087474724300000001
    else if f1 < 4096.0 then
      if Float.is_nan f2 then
        0.0108950427
      else if f2 < 1024.0 then
        0.00245473837
      else
        0.0108950427
    else
      if Float.is_nan f0 then
        0.0087474724300000001
      else if f0 < 32.0 then
        0.038354840100000002
      else
        0.0087474724300000001

let tree_9 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  if Float.is_nan f5 then
    if Float.is_nan f2 then
      if Float.is_nan f0 then
        0.0078849969399999997
      else if f0 < 32.0 then
        0.028674567099999999
      else
        0.0078849969399999997
    else if f2 < 2048.0 then
      if Float.is_nan f2 then
        0.0089468518299999997
      else if f2 < 1024.0 then
        0.00291889464
      else
        0.0089468518299999997
    else
      if Float.is_nan f0 then
        0.0078849969399999997
      else if f0 < 32.0 then
        0.028674567099999999
      else
        0.0078849969399999997
  else if f5 < 32.0 then
    if Float.is_nan f0 then
      if Float.is_nan f5 then
        0.00036479721899999998
      else if f5 < 16.0 then
        0.0025076277099999999
      else
        0.00036479721899999998
    else if f0 < 13.0 then
      if Float.is_nan f5 then
        0.000230809164
      else if f5 < 16.0 then
        -0.0037473011799999999
      else
        0.000230809164
    else
      if Float.is_nan f5 then
        0.00036479721899999998
      else if f5 < 16.0 then
        0.0025076277099999999
      else
        0.00036479721899999998
  else
    if Float.is_nan f2 then
      if Float.is_nan f0 then
        0.0078849969399999997
      else if f0 < 32.0 then
        0.028674567099999999
      else
        0.0078849969399999997
    else if f2 < 2048.0 then
      if Float.is_nan f2 then
        0.0089468518299999997
      else if f2 < 1024.0 then
        0.00291889464
      else
        0.0089468518299999997
    else
      if Float.is_nan f0 then
        0.0078849969399999997
      else if f0 < 32.0 then
        0.028674567099999999
      else
        0.0078849969399999997

let tree_10 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  if Float.is_nan f5 then
    if Float.is_nan f1 then
      if Float.is_nan f0 then
        0.0079707205299999993
      else if f0 < 32.0 then
        0.035600598900000002
      else
        0.0079707205299999993
    else if f1 < 4096.0 then
      if Float.is_nan f2 then
        0.0134255951
      else if f2 < 4096.0 then
        0.0058830143000000003
      else
        0.0134255951
    else
      if Float.is_nan f0 then
        0.0079707205299999993
      else if f0 < 32.0 then
        0.035600598900000002
      else
        0.0079707205299999993
  else if f5 < 32.0 then
    if Float.is_nan f0 then
      if Float.is_nan f5 then
        0.00034661416400000002
      else if f5 < 16.0 then
        0.00238263677
      else
        0.00034661416400000002
    else if f0 < 13.0 then
      if Float.is_nan f1 then
        -0.0036193211599999998
      else if f1 < 2048.0 then
        0.000277290412
      else
        -0.0036193211599999998
    else
      if Float.is_nan f5 then
        0.00034661416400000002
      else if f5 < 16.0 then
        0.00238263677
      else
        0.00034661416400000002
  else
    if Float.is_nan f1 then
      if Float.is_nan f0 then
        0.0079707205299999993
      else if f0 < 32.0 then
        0.035600598900000002
      else
        0.0079707205299999993
    else if f1 < 4096.0 then
      if Float.is_nan f2 then
        0.0134255951
      else if f2 < 4096.0 then
        0.0058830143000000003
      else
        0.0134255951
    else
      if Float.is_nan f0 then
        0.0079707205299999993
      else if f0 < 32.0 then
        0.035600598900000002
      else
        0.0079707205299999993

let tree_11 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  if Float.is_nan f5 then
    if Float.is_nan f2 then
      if Float.is_nan f0 then
        0.0070324079099999999
      else if f0 < 32.0 then
        0.026445403700000002
      else
        0.0070324079099999999
    else if f2 < 2048.0 then
      if Float.is_nan f2 then
        0.0080353142699999998
      else if f2 < 1024.0 then
        0.0023074157099999999
      else
        0.0080353142699999998
    else
      if Float.is_nan f0 then
        0.0070324079099999999
      else if f0 < 32.0 then
        0.026445403700000002
      else
        0.0070324079099999999
  else if f5 < 32.0 then
    if Float.is_nan f0 then
      if Float.is_nan f5 then
        0.00032933746100000002
      else if f5 < 16.0 then
        0.00226387638
      else
        0.00032933746100000002
    else if f0 < 13.0 then
      if Float.is_nan f5 then
        0.00030226129500000003
      else if f5 < 16.0 then
        -0.0034784858599999999
      else
        0.00030226129500000003
    else
      if Float.is_nan f5 then
        0.00032933746100000002
      else if f5 < 16.0 then
        0.00226387638
      else
        0.00032933746100000002
  else
    if Float.is_nan f2 then
      if Float.is_nan f0 then
        0.0070324079099999999
      else if f0 < 32.0 then
        0.026445403700000002
      else
        0.0070324079099999999
    else if f2 < 2048.0 then
      if Float.is_nan f2 then
        0.0080353142699999998
      else if f2 < 1024.0 then
        0.0023074157099999999
      else
        0.0080353142699999998
    else
      if Float.is_nan f0 then
        0.0070324079099999999
      else if f0 < 32.0 then
        0.026445403700000002
      else
        0.0070324079099999999

let tree_12 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  if Float.is_nan f5 then
    if Float.is_nan f1 then
      if Float.is_nan f0 then
        0.00680907443
      else if f0 < 32.0 then
        0.0255412795
      else
        0.00680907443
    else if f1 < 2048.0 then
      if Float.is_nan f2 then
        0.0059940763700000003
      else if f2 < 1024.0 then
        0.00070154003300000004
      else
        0.0059940763700000003
    else
      if Float.is_nan f0 then
        0.00680907443
      else if f0 < 32.0 then
        0.0255412795
      else
        0.00680907443
  else if f5 < 32.0 then
    if Float.is_nan f0 then
      if Float.is_nan f5 then
        0.00031292188200000002
      else if f5 < 16.0 then
        0.0021510350099999999
      else
        0.00031292188200000002
    else if f0 < 13.0 then
      if Float.is_nan f1 then
        -0.0033609678499999999
      else if f1 < 2048.0 then
        0.00034232341600000003
      else
        -0.0033609678499999999
    else
      if Float.is_nan f5 then
        0.00031292188200000002
      else if f5 < 16.0 then
        0.0021510350099999999
      else
        0.00031292188200000002
  else
    if Float.is_nan f1 then
      if Float.is_nan f0 then
        0.00680907443
      else if f0 < 32.0 then
        0.0255412795
      else
        0.00680907443
    else if f1 < 2048.0 then
      if Float.is_nan f2 then
        0.0059940763700000003
      else if f2 < 1024.0 then
        0.00070154003300000004
      else
        0.0059940763700000003
    else
      if Float.is_nan f0 then
        0.00680907443
      else if f0 < 32.0 then
        0.0255412795
      else
        0.00680907443

let tree_13 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  if Float.is_nan f5 then
    if Float.is_nan f1 then
      if Float.is_nan f0 then
        0.0069347298699999997
      else if f0 < 32.0 then
        0.031792752399999999
      else
        0.0069347298699999997
    else if f1 < 4096.0 then
      if Float.is_nan f2 then
        0.011550772000000001
      else if f2 < 4096.0 then
        0.00477453042
      else
        0.011550772000000001
    else
      if Float.is_nan f0 then
        0.0069347298699999997
      else if f0 < 32.0 then
        0.031792752399999999
      else
        0.0069347298699999997
  else if f5 < 32.0 then
    if Float.is_nan f0 then
      if Float.is_nan f2 then
        0.0020762600500000001
      else if f2 < 2048.0 then
        0.000264882809
      else
        0.0020762600500000001
    else if f0 < 13.0 then
      if Float.is_nan f5 then
        0.000362146471
      else if f5 < 16.0 then
        -0.0032310285599999999
      else
        0.000362146471
    else
      if Float.is_nan f2 then
        0.0020762600500000001
      else if f2 < 2048.0 then
        0.000264882809
      else
        0.0020762600500000001
  else
    if Float.is_nan f1 then
      if Float.is_nan f0 then
        0.0069347298699999997
      else if f0 < 32.0 then
        0.031792752399999999
      else
        0.0069347298699999997
    else if f1 < 4096.0 then
      if Float.is_nan f2 then
        0.011550772000000001
      else if f2 < 4096.0 then
        0.00477453042
      else
        0.011550772000000001
    else
      if Float.is_nan f0 then
        0.0069347298699999997
      else if f0 < 32.0 then
        0.031792752399999999
      else
        0.0069347298699999997

let tree_14 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  if Float.is_nan f5 then
    if Float.is_nan f2 then
      if Float.is_nan f0 then
        0.0059720668899999997
      else if f0 < 32.0 then
        0.0236458238
      else
        0.0059720668899999997
    else if f2 < 2048.0 then
      if Float.is_nan f2 then
        0.0067197443000000003
      else if f2 < 1024.0 then
        0.00140869233
      else
        0.0067197443000000003
    else
      if Float.is_nan f0 then
        0.0059720668899999997
      else if f0 < 32.0 then
        0.0236458238
      else
        0.0059720668899999997
  else if f5 < 32.0 then
    if Float.is_nan f0 then
      if Float.is_nan f5 then
        0.000238978289
      else if f5 < 16.0 then
        0.0019854721600000001
      else
        0.000238978289
    else if f0 < 13.0 then
      if Float.is_nan f1 then
        -0.0031230559099999998
      else if f1 < 2048.0 then
        0.00039650598800000002
      else
        -0.0031230559099999998
    else
      if Float.is_nan f5 then
        0.000238978289
      else if f5 < 16.0 then
        0.0019854721600000001
      else
        0.000238978289
  else
    if Float.is_nan f2 then
      if Float.is_nan f0 then
        0.0059720668899999997
      else if f0 < 32.0 then
        0.0236458238
      else
        0.0059720668899999997
    else if f2 < 2048.0 then
      if Float.is_nan f2 then
        0.0067197443000000003
      else if f2 < 1024.0 then
        0.00140869233
      else
        0.0067197443000000003
    else
      if Float.is_nan f0 then
        0.0059720668899999997
      else if f0 < 32.0 then
        0.0236458238
      else
        0.0059720668899999997

let tree_15 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  if Float.is_nan f5 then
    if Float.is_nan f1 then
      if Float.is_nan f0 then
        0.0058862352699999999
      else if f0 < 32.0 then
        0.022630093600000002
      else
        0.0058862352699999999
    else if f1 < 2048.0 then
      if Float.is_nan f1 then
        0.0056418967400000001
      else if f1 < 1024.0 then
        0.0017026000399999999
      else
        0.0056418967400000001
    else
      if Float.is_nan f0 then
        0.0058862352699999999
      else if f0 < 32.0 then
        0.022630093600000002
      else
        0.0058862352699999999
  else if f5 < 32.0 then
    if Float.is_nan f0 then
      if Float.is_nan f2 then
        0.00191733241
      else if f2 < 2048.0 then
        0.00019624188999999999
      else
        0.00191733241
    else if f0 < 13.0 then
      if Float.is_nan f5 then
        0.00041181483500000001
      else if f5 < 16.0 then
        -0.00300309411
      else
        0.00041181483500000001
    else
      if Float.is_nan f2 then
        0.00191733241
      else if f2 < 2048.0 then
        0.00019624188999999999
      else
        0.00191733241
  else
    if Float.is_nan f1 then
      if Float.is_nan f0 then
        0.0058862352699999999
      else if f0 < 32.0 then
        0.022630093600000002
      else
        0.0058862352699999999
    else if f1 < 2048.0 then
      if Float.is_nan f1 then
        0.0056418967400000001
      else if f1 < 1024.0 then
        0.0017026000399999999
      else
        0.0056418967400000001
    else
      if Float.is_nan f0 then
        0.0058862352699999999
      else if f0 < 32.0 then
        0.022630093600000002
      else
        0.0058862352699999999

let predict_latency f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 =
  0.0 +. 1.0 *. (tree_0 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_1 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_2 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_3 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_4 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_5 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_6 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_7 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_8 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_9 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_10 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_11 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_12 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_13 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_14 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 +. tree_15 f0 f1 f2 f3 f4 f5 f6 f7 f8 f9)

module Device = struct
  type t = { gpu_core_count : int; memory_bandwidth_gbps : float }

  let create ~gpu_core_count ~memory_bandwidth_gbps =
    if gpu_core_count <= 0 then Error "GPU core count must be positive"
    else if
      not (Float.is_finite memory_bandwidth_gbps)
      || memory_bandwidth_gbps <= 0.0
    then Error "memory bandwidth must be finite and positive"
    else Ok { gpu_core_count; memory_bandwidth_gbps }

  let default =
    match create ~gpu_core_count:8 ~memory_bandwidth_gbps:100.0 with
    | Ok device -> device
    | Error message -> invalid_arg message

  let gpu_core_count device = device.gpu_core_count
  let memory_bandwidth_gbps device = device.memory_bandwidth_gbps
end

module Megakernel = struct
  type qkv_rope_tile = {
    threads_per_threadgroup : int;
    simdgroups_per_threadgroup : int;
    pairs_per_threadgroup : int;
    grid_threadgroups : int;
  }

  type lm_head_tile = {
    stage1_threadgroups : int;
    stage1_threads : int;
    columns_per_thread : int;
  }

  let select_qkv_rope_tile ~device ~total_pairs =
    let cores = Device.gpu_core_count device in
    if cores >= 16 then
      let simdgroups = 4 in
      let threads = simdgroups * 32 in
      let pairs_per_tg = simdgroups in
      let tgs = (total_pairs + pairs_per_tg - 1) / pairs_per_tg in
      {
        threads_per_threadgroup = threads;
        simdgroups_per_threadgroup = simdgroups;
        pairs_per_threadgroup = pairs_per_tg;
        grid_threadgroups = tgs;
      }
    else
      let simdgroups = 8 in
      let threads = simdgroups * 32 in
      let pairs_per_tg = simdgroups in
      let tgs = (total_pairs + pairs_per_tg - 1) / pairs_per_tg in
      {
        threads_per_threadgroup = threads;
        simdgroups_per_threadgroup = simdgroups;
        pairs_per_threadgroup = pairs_per_tg;
        grid_threadgroups = tgs;
      }

  let select_lm_head_tile ~device ~vocab_size =
    let cores = Device.gpu_core_count device in
    if cores >= 16 then
      let tgs = 256 in
      let threads = 256 in
      let cols_per_thread = (vocab_size + (tgs * threads) - 1) / (tgs * threads) in
      {
        stage1_threadgroups = tgs;
        stage1_threads = threads;
        columns_per_thread = cols_per_thread;
      }
    else
      let tgs = 128 in
      let threads = 256 in
      let cols_per_thread = (vocab_size + (tgs * threads) - 1) / (tgs * threads) in
      {
        stage1_threadgroups = tgs;
        stage1_threads = threads;
        columns_per_thread = cols_per_thread;
      }
end
