type kernel =
  | Matmul of int * int * int
  | Fused of int * int * int
  | Linear of int * int * int * bool
  | Q8 of int * int * int * bool

let kernel_shape graph =
  Ir.Graph.nodes graph
  |> List.find_map (fun node ->
         match Ir.node_op node with
         | Ir.Op.Matmul { m; n; k } -> Some (Matmul (m, n, k))
         | Ir.Op.Fused_matmul_bias { m; n; k } -> Some (Fused (m, n, k))
         | Ir.Op.Q8_linear { m; n; k; bias } -> Some (Q8 (m, n, k, bias))
         | Ir.Op.Linear { m; n; k; bias } -> Some (Linear (m, n, k, bias))
         | _ -> None)

let emit_q8 ~m ~n ~k ~has_bias =
  let header =
    if has_bias then
      "define void @llmopt_q8_linear(ptr %a, ptr %b, ptr %scale, ptr %bias, ptr %c) {"
    else "define void @llmopt_q8_linear(ptr %a, ptr %b, ptr %scale, ptr %c) {"
  in
  let bias_lines =
    if has_bias then
      [ "  %bias.ptr = getelementptr float, ptr %bias, i64 %j"
      ; "  %bias.value = load float, ptr %bias.ptr, align 4"
      ; "  %with.bias = fadd float %acc.next, %bias.value"
      ]
    else [ "  %with.bias = fadd float %acc.next, 0.000000e+00" ]
  in
  let source_lines =
    [ "; ModuleID = 'llmopt-q8'"
    ; "; generated by the OCaml graph backend"
    ; ("target triple = " ^ String.make 1 (Char.chr 34)
       ^ "arm64-apple-macosx26.0.0" ^ String.make 1 (Char.chr 34))
    ; header
    ; "entry:"
    ; "  br label %row"
    ; "row:"
    ; "  %i = phi i64 [ 0, %entry ], [ %i.next, %row.inc ]"
    ; "  br label %col"
    ; "col:"
    ; "  %j = phi i64 [ 0, %row ], [ %j.next, %col.inc ]"
    ; "  br label %inner"
    ; "inner:"
    ; "  %kk = phi i64 [ 0, %col ], [ %kk.next, %inner.inc ]"
    ; "  %acc = phi float [ 0.000000e+00, %col ], [ %acc.next, %inner.inc ]"
    ; Printf.sprintf "  %%a.row = mul i64 %%i, %d" k
    ; "  %a.index = add i64 %a.row, %kk"
    ; "  %a.ptr = getelementptr float, ptr %a, i64 %a.index"
    ; "  %a.value = load float, ptr %a.ptr, align 4"
    ; Printf.sprintf "  %%b.row = mul i64 %%j, %d" k
    ; "  %b.index = add i64 %b.row, %kk"
    ; "  %b.ptr = getelementptr i8, ptr %b, i64 %b.index"
    ; "  %b.value = load i8, ptr %b.ptr, align 1"
    ; "  %b.float = sitofp i8 %b.value to float"
    ; "  %scale.ptr = getelementptr float, ptr %scale, i64 %j"
    ; "  %scale.value = load float, ptr %scale.ptr, align 4"
    ; "  %scaled = fmul float %b.float, %scale.value"
    ; "  %product = fmul float %a.value, %scaled"
    ; "  %acc.next = fadd float %acc, %product"
    ; "  %kk.next = add i64 %kk, 1"
    ; Printf.sprintf "  %%inner.done = icmp eq i64 %%kk.next, %d" k
    ; "  br i1 %inner.done, label %store, label %inner.inc"
    ; "inner.inc:"
    ; "  br label %inner"
    ; "store:"
    ]
    @ bias_lines
    @ [ Printf.sprintf "  %%c.row = mul i64 %%i, %d" n
      ; "  %c.index = add i64 %c.row, %j"
      ; "  %c.ptr = getelementptr float, ptr %c, i64 %c.index"
      ; "  store float %with.bias, ptr %c.ptr, align 4"
      ; "  br label %col.inc"
      ; "col.inc:"
      ; "  %j.next = add i64 %j, 1"
      ; Printf.sprintf "  %%col.done = icmp eq i64 %%j.next, %d" n
      ; "  br i1 %col.done, label %row.inc, label %col"
      ; "row.inc:"
      ; "  %i.next = add i64 %i, 1"
      ; Printf.sprintf "  %%row.done = icmp eq i64 %%i.next, %d" m
      ; "  br i1 %row.done, label %exit, label %row"
      ; "exit:"
      ; "  ret void"
      ; "}"
      ]
  in
  Ok (String.concat "\n" source_lines ^ "\n")

let emit graph =
  let q8_kernel =
    Ir.Graph.nodes graph
    |> List.find_map (fun node ->
           match Ir.node_op node with
           | Ir.Op.Q8_linear { m; n; k; bias } -> Some (m, n, k, bias)
           | _ -> None)
  in
  match q8_kernel with
  | Some (m, n, k, bias) -> emit_q8 ~m ~n ~k ~has_bias:bias
  | None ->
  match kernel_shape graph with
  | None -> Error "LLVM emitter expects one supported kernel node"
  | Some kernel ->
      let m, n, k, has_bias, linear =
        match kernel with
        | Matmul (m, n, k) -> m, n, k, false, false
        | Fused (m, n, k) -> m, n, k, true, false
        | Linear (m, n, k, bias) -> m, n, k, bias, true
        | Q8 _ -> failwith "Q8 kernel must use the dedicated emitter"
      in
      let header =
        if has_bias then
          "define void @llmopt_matmul(ptr %a, ptr %b, ptr %bias, ptr %c) {"
        else "define void @llmopt_matmul(ptr %a, ptr %b, ptr %c) {"
      in
      let bias_lines =
        if has_bias then
          [ "  %bias.ptr = getelementptr float, ptr %bias, i64 %j"
          ; "  %bias.value = load float, ptr %bias.ptr, align 4"
          ; "  %stored = fadd float %acc.next, %bias.value"
          ]
        else [ "  %stored = fadd float %acc.next, 0.000000e+00" ]
      in
      let b_index_lines =
        if linear then
          [ Printf.sprintf "  %%b.col = mul i64 %%j, %d" k
          ; "  %b.index = add i64 %b.col, %kk"
          ]
        else
          [ Printf.sprintf "  %%b.row = mul i64 %%kk, %d" n
          ; "  %b.index = add i64 %b.row, %j"
          ]
      in
      let source_lines =
        [ "; ModuleID = 'llmopt'"
        ; "; generated by the OCaml graph backend"
        ; "target triple = \"arm64-apple-macosx26.0.0\""
        ; header
        ; "entry:"
        ; "  br label %row"
        ; "row:"
        ; "  %i = phi i64 [ 0, %entry ], [ %i.next, %row.inc ]"
        ; "  br label %col"
        ; "col:"
        ; "  %j = phi i64 [ 0, %row ], [ %j.next, %col.inc ]"
        ; "  br label %inner"
        ; "inner:"
        ; "  %kk = phi i64 [ 0, %col ], [ %kk.next, %inner.inc ]"
        ; "  %acc = phi float [ 0.000000e+00, %col ], [ %acc.next, %inner.inc ]"
        ; Printf.sprintf "  %%a.row = mul i64 %%i, %d" k
        ; "  %a.index = add i64 %a.row, %kk"
        ; "  %a.ptr = getelementptr float, ptr %a, i64 %a.index"
        ; "  %a.value = load float, ptr %a.ptr, align 4"
        ]
        @ b_index_lines
        @ [ "  %b.ptr = getelementptr float, ptr %b, i64 %b.index"
          ; "  %b.value = load float, ptr %b.ptr, align 4"
          ; "  %product = fmul float %a.value, %b.value"
          ; "  %acc.next = fadd float %acc, %product"
          ; "  %kk.next = add i64 %kk, 1"
          ; Printf.sprintf "  %%inner.done = icmp eq i64 %%kk.next, %d" k
          ; "  br i1 %inner.done, label %store, label %inner.inc"
          ; "inner.inc:"
          ; "  br label %inner"
          ; "store:"
          ]
        @ bias_lines
        @ [ Printf.sprintf "  %%c.row = mul i64 %%i, %d" n
          ; "  %c.index = add i64 %c.row, %j"
          ; "  %c.ptr = getelementptr float, ptr %c, i64 %c.index"
          ; "  store float %stored, ptr %c.ptr, align 4"
          ; "  br label %col.inc"
          ; "col.inc:"
          ; "  %j.next = add i64 %j, 1"
          ; Printf.sprintf "  %%col.done = icmp eq i64 %%j.next, %d" n
          ; "  br i1 %col.done, label %row.inc, label %col"
          ; "row.inc:"
          ; "  %i.next = add i64 %i, 1"
          ; Printf.sprintf "  %%row.done = icmp eq i64 %%i.next, %d" m
          ; "  br i1 %row.done, label %exit, label %row"
          ; "exit:"
          ; "  ret void"
          ; "}"
          ]
      in
      Ok (String.concat "\n" source_lines ^ "\n")
